server {
    listen 80;
    server_name _;
    root /var/www/html/public;

    index index.php;
    client_max_body_size 100M; #максимальный размер загрузок

    # Логи в stdout/stderr для docker logs
    access_log /dev/stdout;
    error_log /dev/stderr;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

     location ~ \.php$ {
        fastcgi_pass unix:/run/php/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }
}